language: python
python:
    - "2.7"
cache: pip
before_install:
    - "git config --global user.email $GITHUB_EMAIL"
    - "git config --global user.name 'Travis Deploy'"
install: "pip install -r requirements.txt"
before_script:
    - "git init output"
    - "git -C output pull https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git"
script: "pelican -s publishconf.py"
after_success:
    - "cd output; git add -A"
    - 'git commit -m "$TRAVIS_COMMIT_MESSAGE"'
    - "git push https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git"
