language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"
before_script:
    - "mkdir output; cd output"
    - "git init"
    - "git pull https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git"
    - "cd .."
script: "pelican -s publishconf.py"
after_success:
    - "cd output; git add ."
    - "git status"
