branches:
    only:
        - master
skip_tags: true
max_jobs: 1
environment:
    GITHUB_TOKEN:
        secure: EGTXnwQ9mmxtdvXYwz3eVjHEww+mUL0Zusw1eE8TEQlbZacBGgdBRksDIpPART07
    GITHUB_REPO: cprieto.github.io
    GITHUB_USER: cprieto
    GITHUB_EMAIL:
        secure: 9HtcjxwfWvnX1qgYJJPJmg==
init:
    - git config --global user.email $(GITHUB_EMAIL)
    - git config --global user.name 'Travis Deploy'
install:
    - pip install -q -r requirements
before_build:
    - git init output
    - git -C output pull https://$(GITHUB_TOKEN)@github.com/$(GITHUB_USERNAME)/$(GITHUB_REPO).git
build_script:
    - pelican -s publishconf.py
artifacts:
    - path: output
      name: output
